# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01ec78e2bd4f5b346acba236bcd5130014d84322a2f055120b3604f67e2f44e2786233464da4eb3b847cb00e5149f71b619c13b218eafb83ce5fefbab6c9cf79

test:
  secret_key_base: dba9516d8e01ad9a943c44be3f59d2f3e8f2d004656bc1cde7bdf03367ad72f274bfcef0ce53e904e51da4090e58bc021f3843b5dbd246c3ea7f2307d3739244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
